#! /bin/bash

LOG_LEVEL="warning"
YT_DLP="FALSE"
FORMAT=""
INPUT_FILE=""
N16=$(cat /dev/urandom | tr -dc '1-9' | head -c16)
N12=$(cat /dev/urandom | tr -dc '1-9' | head -c12)
OUTPUT_FILE="${N16}.mp4"
REFERER=""
M3U8=FALSE
DOWNLOAD_INDEX=0
RECONNECT=TRUE
START_TIME=""
END_TIME=""
VARIABLE_FRAME_RATE=FALSE
AUDIO=TRUE
ROTATE="0"
CROP=""
ASPECT=""

while getopts ":-:" OPT; do
  OPT="-${OPT}${OPTARG}"
  OPTARG="${!OPTIND}"
  if [ "${OPT}" = "--log-level" ]; then
    LOG_LEVEL="${OPTARG}"
    shift
  elif [ "${OPT}" = "--yt-dlp" ]; then
    YT_DLP="TRUE"
  elif [ "${OPT}" = "--format" ]; then
    FORMAT="${OPTARG}"
    shift
  elif [ "${OPT}" = "--input-file" ]; then
    INPUT_FILE="${OPTARG}"
    shift
  elif [ "${OPT}" = "--output-file" ]; then
    OUTPUT_FILE="${OPTARG}"
    shift
  elif [ "${OPT}" = "--referer" ]; then
    REFERER="${OPTARG}"
    shift
  elif [ "${OPT}" = "--m3u8" ]; then
    M3U8="TRUE"
  elif [ "${OPT}" = "--no-reconnect" ]; then
    RECONNECT="FALSE"
  elif [ "${OPT}" = "--start" ]; then
    START_TIME="${OPTARG}"
    shift
  elif [ "${OPT}" = "--end" ]; then
    END_TIME="${OPTARG}"
    shift
  elif [ "${OPT}" = "--variable-frame-rate" ]; then
    VARIABLE_FRAME_RATE=TRUE
  elif [ "${OPT}" = "--no-audio" ]; then
    AUDIO="FALSE"
  elif [ "${OPT}" = "--rotate" ]; then
    ROTATE="${OPTARG}"
    shift
  elif [ "${OPT}" = "--crop" ]; then
    CROP="${OPTARG}"
    shift
  elif [ "${OPT}" = "--aspect" ]; then
    ASPECT="${OPTARG}"
    shift
  else
    echo "Undefined option: ${OPT} ${OPTARG}"
    exit 1
  fi
done

if [ "${M3U8}" = "TRUE" ]; then
  INPUT_FILE_DIR="$(dirname ${INPUT_FILE})/"
  DOWNLOAD_INDEX=$(ls download*.m3u8 2>/dev/null | wc -l)
  CURL_HEADER=""
  if [ ! "${REFERER}" = "" ]; then
    CURL_HEADER="-H 'Referer: ${REFERER}'"
  fi
  echo "curl ${CURL_HEADER} \"${INPUT_FILE}\" | strings > download${DOWNLOAD_INDEX}.m3u8"
  curl ${CURL_HEADER} "${INPUT_FILE}" | strings > download${DOWNLOAD_INDEX}.m3u8
  cat download${DOWNLOAD_INDEX}.m3u8 | sed -r "s/^(()|(#.*)|(https?:\/\/.*))$/\1/;t;s/^/${INPUT_FILE_DIR//\//\\/}/" | grep -v \# > download${DOWNLOAD_INDEX}.list
  vim download${DOWNLOAD_INDEX}.list
  INPUT_FILES=()
  while read INPUT_FILE; do
    if [ ! "${INPUT_FILE}" = "" ]; then
      INPUT_FILES+=("${INPUT_FILE}")
    fi
  done < download${DOWNLOAD_INDEX}.list
  mkdir -p _temp${DOWNLOAD_INDEX}
  cd _temp${DOWNLOAD_INDEX}
  CONCAT_FILE="concat.list"
  for a in "${!INPUT_FILES[@]}"; do
    INPUT_FILE=${INPUT_FILES[$a]}
    OUTPUT_FILE=$(printf "${N12}%04d.mp4" ${a})
    echo "ffmpeg-video --format mpegts --input-file ${INPUT_FILE} --output-file ${OUTPUT_FILE}"
    ffmpeg-video --format mpegts --input-file ${INPUT_FILE} --output-file ${OUTPUT_FILE}
    echo "file '${OUTPUT_FILE}'" >> ${CONCAT_FILE}
  done
  OUTPUT_FILE="${N16}.mp4"
  echo "ffmpeg-video --input-file ${CONCAT_FILE} --output-file ../${OUTPUT_FILE} --format concat --no-reconnect"
  ffmpeg-video --input-file ${CONCAT_FILE} --output-file ../${OUTPUT_FILE} --format concat --no-reconnect
  cd ..
  rm -rfv download${DOWNLOAD_INDEX}.m3u8 download${DOWNLOAD_INDEX}.list _temp${DOWNLOAD_INDEX}
  exit
fi

FFMPEG_INPUT_OPT="-loglevel ${LOG_LEVEL} -err_detect ignore_err"
FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -fflags +discardcorrupt"
FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -protocol_whitelist crypto,data,file,https,tcp,tls"
if [ ! "${REFERER}" = "" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -referer ${REFERER}"
fi
if [ "${RECONNECT}" = "TRUE" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -user_agent \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36\""
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 12"
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -multiple_requests 1"
fi
if [ "${M3U8}" = "TRUE" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -seg_max_retry 12 -max_reload 1 -rw_timeout 3000000"
fi
if [ "${START_TIME}" != "" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -ss ${START_TIME}"
fi
if [ "${END_TIME}" != "" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -to ${END_TIME}"
fi
if [ "${FORMAT}" != "" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -f ${FORMAT}"
fi
FFMPEG_OUTPUT_OPT_VF="scale=trunc(iw/2)*2:trunc(ih/2)*2"
FFMPEG_OUTPUT_OPT="-tag:v hvc1 -movflags +faststart"
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -max_muxing_queue_size 9999"
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -c:v libx265 -level:v 4.0"
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -b_strategy 2 -bf 2"
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -flags cgop -coder ac -pix_fmt yuv420p -crf 18"
if [ "${VARIABLE_FRAME_RATE}" = "TRUE" ]; then
  FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -fps_mode vfr"
fi
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -bufsize 100M"
if [ "${AUDIO}" = "TRUE" ]; then
  FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -map 0:a:0? -c:a aac -aac_coder twoloop -ac 2 -ar 48000"
fi
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -map 0:v:0? -map_chapters -1 -map -0:s -map_metadata -1"
FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -fflags +bitexact -flags:v +bitexact -flags:a +bitexact"
if [ "${ROTATE}" != "" ] && [ "$ROTATE" != "0" ]; then
  if [ "${ROTATE}" = "90" ]; then
    FFMPEG_OUTPUT_OPT_VF="${FFMPEG_OUTPUT_OPT_VF},transpose=1"
  elif [ "${ROTATE}" = "180" ]; then
    FFMPEG_OUTPUT_OPT_VF="${FFMPEG_OUTPUT_OPT_VF},hflip,vflip"
  elif [ "${ROTATE}" = "270" ]; then
    FFMPEG_OUTPUT_OPT_VF="${FFMPEG_OUTPUT_OPT_VF},transpose=2"
  fi
fi
if [ "${CROP}" != "" ]; then
  FFMPEG_OUTPUT_OPT_VF="${FFMPEG_OUTPUT_OPT_VF},crop=${CROP}"
fi
if [ "${ASPECT}" != "" ]; then
  FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -aspect ${ASPECT}"
fi
if [ "${FFMPEG_OUTPUT_OPT_VF}" != "" ]; then
  FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -vf \"${FFMPEG_OUTPUT_OPT_VF}\""
fi
if [ "${INPUT_FILE}" != "" ]; then
  if [ "${YT_DLP}" = "FALSE" ]; then
    echo "ffmpeg ${FFMPEG_INPUT_OPT} -i \"${INPUT_FILE}\" ${FFMPEG_OUTPUT_OPT} ${OUTPUT_FILE}"
    bash -c "ffmpeg ${FFMPEG_INPUT_OPT} -i \"${INPUT_FILE}\" ${FFMPEG_OUTPUT_OPT} ${OUTPUT_FILE}"
  else
    YT_DLP_OPT="--recode-video mp4"
    YT_DLP_OPT="${YT_DLP_OPT} --format-sort \"vcodec:h265,quality,res,fps,hdr:12,acodec:aac\""
    YT_DLP_OPT="${YT_DLP_OPT} --downloader-args 'ffmpeg:${FFMPEG_INPUT_OPT}'"
    YT_DLP_OPT="${YT_DLP_OPT} --postprocessor-args 'ffmpeg:${FFMPEG_OUTPUT_OPT}'"
    YT_DLP_OPT="${YT_DLP_OPT} --output ${OUTPUT_FILE}"
    echo "yt-dlp ${YT_DLP_OPT} \"${INPUT_FILE}\""
    bash -c "yt-dlp ${YT_DLP_OPT} \"${INPUT_FILE}\""
  fi
  echo "chmod 600 ${OUTPUT_FILE}"
  chmod 600 ${OUTPUT_FILE}
fi

if [ "${M3U8}" = "TRUE" ]; then
  rm -rfv download${DOWNLOAD_INDEX}.m3u8
fi
