#! /bin/bash

LOG_LEVEL="warning"
LIST="FALSE"
INPUT_FILES=()
REFERER=""
ROTATE="0"
CROP=""
ASPECT=""
N13=$(cat /dev/urandom | tr -dc '1-9' | head -c13)

while getopts ":-:" OPT; do
  OPT="-${OPT}${OPTARG}"
  OPTARG="${!OPTIND}"
  if [ "${OPT}" = "--log-level" ]; then
    LOG_LEVEL="${OPTARG}"
    shift
  elif [ "${OPT}" = "--list" ]; then
    while read INPUT_FILE; do
      if [ ! "${INPUT_FILE}" = "" ]; then
        INPUT_FILES+=("${INPUT_FILE}")
      fi
    done
  elif [ "${OPT}" = "--input-file" ]; then
    INPUT_FILES+=("${OPTARG}")
    shift
  elif [ "${OPT}" = "--referer" ]; then
    REFERER="${OPTARG}"
    shift
  elif [ "${OPT}" = "--rotate" ]; then
    ROTATE="${OPTARG}"
    shift
  elif [ "${OPT}" = "--crop" ]; then
    CROP="${OPTARG}"
    shift
  elif [ "${OPT}" = "--aspect" ]; then
    ASPECT="${OPTARG}"
    shift
  else
    echo "Undefined option: ${OPT} ${OPTARG}"
    exit 1
  fi
done

FFMPEG_INPUT_OPT="-loglevel ${LOG_LEVEL} -err_detect ignore_err"
FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -fflags +discardcorrupt"
FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -protocol_whitelist crypto,data,file,https,tcp,tls"
FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -user_agent \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36\""
if [ ! "${REFERER}" = "" ]; then
  FFMPEG_INPUT_OPT="${FFMPEG_INPUT_OPT} -referer ${REFERER}"
fi
FFMPEG_OUTPUT_OPT="-q:v 1 -map_chapters -1 -map -0:s -map_metadata -1"
if [ "${ROTATE}" != "" ] && [ "$ROTATE" != "0" ]; then
  if [ "${ROTATE}" = "90" ]; then
    FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -vf transpose=1"
  elif [ "${ROTATE}" = "180" ]; then
    FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -vf hflip,vflip"
  elif [ "${ROTATE}" = "270" ]; then
    FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -vf transpose=2"
  fi
fi
if [ "${CROP}" != "" ]; then
  FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -vf crop=${CROP}"
fi
if [ "${ASPECT}" != "" ]; then
  FFMPEG_OUTPUT_OPT="${FFMPEG_OUTPUT_OPT} -aspect ${ASPECT}"
fi
for a in "${!INPUT_FILES[@]}"; do
  a3=$(printf "%03d" $a)
  echo "ffmpeg ${FFMPEG_INPUT_OPT} -i \"${INPUT_FILES[$a]}\" ${FFMPEG_OUTPUT_OPT} ${N13}${a3}.jpg"
  bash -c "ffmpeg ${FFMPEG_INPUT_OPT} -i \"${INPUT_FILES[$a]}\" ${FFMPEG_OUTPUT_OPT} ${N13}${a3}.jpg"
  echo "chmod 600 ${N13}${a3}.jpg"
  chmod 600 ${N13}${a3}.jpg
done
