#! /bin/bash

if [ $# -ge 1 ]; then
  n16=$(cat /dev/urandom | tr -dc '1-9' | head -c16)
  ffmpeg -framerate 3 -i "$1" -filter_complex "[0:v] scale=1024:-1,split [a][b];[a] palettegen [p];[b][p] paletteuse" ${n16}.gif
fi

