#! /bin/bash

if [ $# -ge 1 ]; then
  rm -rf _temp && mkdir _temp
  N=0
  SRCS=""
  ORIG=""
  for f in $(ls $@); do
    echo "convert +repage -units PixelsPerInch ${f} -density 300 -resize 3840x _temp/${N}.pdf"
    convert +repage -units PixelsPerInch ${f} -density 300 -resize 3840x _temp/${N}.pdf
    ORIG="${ORIG} ${f}"
    SRCS="${SRCS} _temp/${N}.pdf"
    N=$((N + 1))
  done
  echo "SRCS: ${SRCS}"
  n16=$(cat /dev/urandom | tr -dc '1-9' | head -c16)
  gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH -sOutputFile=${n16}.pdf ${SRCS}
  chmod 600 $n16.pdf
  if [ ! -d _trash ]; then
    mkdir _trash
  fi
  echo "mv $ORIG _trash"
  mv $ORIG _trash
  rm -rf _temp 
fi

